version: "3"
services:
  app:
    build:
      context: ./Web
      dockerfile: Dockerfile
    image: media_web:v1.0.0
    container_name: media_app
    environment:
      BASIC_AUTH_PASS: "ascade"
      BASIC_AUTH_USER: "media"
      BASIC_ENABLED: "true"
      BROWSER_BASE_URL: "http://ext-host0004.ascade.co.jp:8888"
      ES_URL: "http://db:9200"
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "8080"
    networks:
      - default
    volumes:
      - ${PWD}/Web/.editorconfig:/opt/MeDIA_Web/.editorconfig:rw
      - ${PWD}/Web/.eslintrc.js:/opt/MeDIA_Web/.eslintrc.js:rw
      - ${PWD}/Web/.prettierrc:/opt/MeDIA_Web/.prettierrc:rw
      - ${PWD}/Web/data:/opt/MeDIA_Web/data:rw
      - ${PWD}/Web/nuxt.config.js:/opt/MeDIA_Web/nuxt.config.js:rw
      - ${PWD}/Web/package-lock.json:/opt/MeDIA_Web/package-lock.json:rw
      - ${PWD}/Web/package.json:/opt/MeDIA_Web/package.json:rw
      - ${PWD}/Web/README.md:/opt/MeDIA_Web/README.md:rw
      - ${PWD}/Web/src:/opt/MeDIA_Web/src:rw
      - ${PWD}/Web/tests:/opt/MeDIA_Web/tests:rw
    restart: always
    command: ["npm", "run", "start"]
    # command: ["tail", "-f", "/dev/null"]

  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: media_db
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "media_elasticsearch_passwd"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=warning:stderr:utctime"
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - default
    volumes:
      - ${PWD}/Elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ${PWD}/Elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ${PWD}/Elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: local0
        tag: "{{.Name}}"

  web:
    image: nginx:1.17
    container_name: media_web
    environment:
      SERVER_NAME: "ext-host0004.ascade.co.jp"
      APP_URL: "http://app:8080"
    networks:
      - default
    ports:
      - "0.0.0.0:8888:80"
    volumes:
      - ${PWD}/Nginx/nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf.tmpl:ro
    restart: always
    command: /bin/sh -c "envsubst '$$SERVER_NAME$$APP_URL' < /etc/nginx/conf.d/nginx.conf.tmpl > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

networks:
  default:
    external:
      name: media_network
