version: "3"
services:
  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    image: media_web:v1.0.0
    container_name: media_web
    ports:
      - 8080:8080 # TODO for development
    volumes:
      - ${PWD}/Web:/opt/MeDIA_Web
    command: ["tail", "-f", "/dev/null"]
    restart: always

  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: media_db
    networks:
      - default
    ports:
      - 9200:9200 # TODO for development
      - 9300:9300 # TODO for development
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "media_elasticsearch_passwd"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # TODO for development
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${PWD}/Elasticsearch/data:/usr/share/elasticsearch/data
      - ${PWD}/Elasticsearch/logs:/usr/share/elasticsearch/logs
      - ${PWD}/Elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    restart: always

  kibana: # TODO for development
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: media_kibana
    networks:
      - default
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://db:9200"
    restart: always
