version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: media_app:1.0.1
    container_name: media_app
    environment:
      BASIC_AUTH_PASS: "pass"
      BASIC_AUTH_USER: "media"
      BASIC_ENABLED: "true"
      BROWSER_BASE_URL: "http://127.0.0.1:8888"
      ES_URL: "http://db:9200"
      NUXT_HOST: "0.0.0.0"
      NUXT_PORT: "8080"
    networks:
      - default
    volumes:
      - ${PWD}/app/data:/app/data
    restart: on-failure
    command: ["wait-for-it", "-s", "db:9200", "--", "yarn", "start"]
    logging:
      driver: syslog
      options:
        syslog-facility: local0
        tag: "{{.Name}}"

  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: media_db
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "media_elasticsearch_passwd"
      ES_JAVA_OPTS: "-Xms4g -Xmx4g -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=warning:stderr:utctime"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - default
    volumes:
      - ${PWD}/Elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ${PWD}/Elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ${PWD}/Elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    restart: on-failure
    logging:
      driver: syslog
      options:
        syslog-facility: local0
        tag: "{{.Name}}"

networks:
  default:
    external:
      name: media_network
