version: "3"
services:
  cli:
    build:
      context: ./CLI
      dockerfile: Dockerfile
    image: media_cli:v1.0.0
    container_name: media_cli
    volumes:
      - ${PWD}/CLI:/opt/MeDIA_CLI
    command: ["tail", "-f", "/dev/null"]
    restart: always

  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    image: media_web:v1.0.0
    container_name: media_web
    # ports:
    #   - 80:80
    #   - 443:443
    volumes:
      - ${PWD}/Web:/opt/MeDIA_Web
    command: ["tail", "-f", "/dev/null"]
    restart: always

  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: media_db
    networks:
      - default
    # ports:
    #   - 9200:9200
    #   - 9300:9300
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "media_elasticsearch_passwd"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${PWD}/Elasticsearch/data:/usr/share/elasticsearch/data
      - ${PWD}/Elasticsearch/logs:/usr/share/elasticsearch/logs
      - ${PWD}/Elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    restart: always
